### ISSUE TITLE
Example would aid in starting

### ISSUE THREAD

**Issue by paulirotta** [jq-rs/mles-rs#129]
Looks very nice. I like the minimalist and clear interface.

It will take some work to evaluate so easing that may help with adoption.

My questions after first look are the security model or how you would integrate one (authentication, keys ..) and redundant top level server setup to avoid a single point of failure without the looping issue which you mention there are guards for.

**Comment by jq-rs** [comment]
In theory you could configure peers to point each others or set them to a ring. Loop prevention would then reorganize the hierarchy based on available connections. I say in theory, because you cannot successfully use history anymore and you'd probably need something like anycast for servers anyway to guarantee full client connectivity.

If small top level hickups are fine, then a large peer history config should be able to handle them so that no messages are eventually lost.

**Comment by jq-rs** [comment]
Regarding the key sharing for authentication, I think it is out-of-scope for the Mles service itself. I am sure the are a lot of IKE stuff out there that can be used. If you come up with a best practice, to top level resiliency or key handling, please do share it, I can then add it as an example for all. Let me know if you need more info.

**Comment by jq-rs** [comment]
As this issue is not active anymore, I'll close this for now. PRs are always welcome even for best practices for the library.

**Comment by jq-rs** [comment]
As load-balancing support is coming at some point, this is reopened.

The current plan is to include configurable CID support for peer servers. This allows to configure peers into protecting pairs or to a ring for high availability. The Mles protocol spec needs to be updated to describe this.

**Comment by jq-rs** [comment]
#139

**Comment by jq-rs** [comment]
Spec updated

**Comment by paulirotta** [comment]
Deprecated
